name: Sync OTP Releases
on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.7.2

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: release_sync/vendor/bundle
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-release-sync-gems-${{ hashFiles('release_sync/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-release-sync-gems-

      - name: Install gems
        working-directory: release_sync
        run: bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Sync Releases
        working-directory: release_sync
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: rake sync_releases
